### ISSUE TITLE
Why not using UNIXSocket & UNIXServer instead of Redis ?

### ISSUE THREAD

**Issue by bew** [hyronx/plugal#1]
Last week I had the (almost) same idea as you for making plugins in Crystal, with the concepts of PluginHost (your Receiver) and Plugins (your Providers) which could serve multiple PluginHosts (let's be crazy !)

For the communication part I also thought about a binary protocol, but for the transport, I wanted to use UNIX sockets.. As I don't (and don't want to) have a Redis server on my computer.

What do you think ? Is it lighter/better ?

If the 2 are similar but one want it's redis server to be used, we could maybe implement 2 backends for the transport so the user could choose at compile-time..

**Comment by fabianloewe** [comment]
Your idea is very good. We could create an interface for which we provide some 'official' backends like UNIX sockets and Redis and users can then choose to implement other backends, too.

UNIX sockets might also perform better than Redis but this actually just was a toy project to familiarize myself with Crystal and to decide if it is a language I want to use for my own little projects. This is also why I haven't worked any further on this project but if you are interested in it I will take the time to improve it.

**Comment by bew** [comment]
As currently the Unix sockets are not working for DGRAM (see my issue [here](https://github.com/crystal-lang/crystal/issues/3214) ), and because using DGRAM Unix socket type would be the easier way for implementing this, I think it's preferable to wait until Unix sockets are officially fixed before going forward..

**Comment by bew** [comment]
I'm not interested in Crystal dev anymore
